<?php

namespace Database\Seeders;

use App\Models\TechSkill;
use Illuminate\Database\Seeder;

class TechSkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $techSkills = [
            "Java",
            "C",
            "C++",
            "C#",
            "Python",
            "Visual Basic .NET",
            "PHP",
            "JavaScript",
            "Go",
            "Swift",
            "Objective-C",
            "SQL",
            "Ruby",
            "Perl",
            "Scala",
            "Assembly language",
            "PL/SQL",
            "MATLAB",
            "ABAP",
            "COBOL",
            "Lisp",
            "Fortran",
            "Pascal",
            "Ada",
            "Prolog",
            "Erlang",
            "Haskell",
            "R",
            "Delphi/Object Pascal",
            "F#",
            "Julia",
            "D",
            "Rust",
            "Smalltalk",
            "Clojure",
            "Elixir",
            "Scheme",
            "Tcl",
            "VBScript",
            "Groovy",
            "Kotlin",
            "SAS",
            "PL/I",
            "Bash",
            "Ocaml",
            "T-SQL",
            "PowerShell",
            "ActionScript",
            "TypeScript",
            "Objective-C++",
            "HiveQL",
            "Transact-SQL",
            "PL/B",
            "SQLPL",
            "Dart",
            "XSLT",
            "Logo",
            "Standard ML",
            "C Shell",
            "Eiffel",
            "Puppet",
            "Alice",
            "Logtalk",
            "Apex",
            "LabVIEW",
            "Propeller Spin",
            "OpenCL",
            "Agda",
            "IDL",
            "AWK",
            "Coq",
            "Scilab",
            "VHDL",
            "AppleScript",
            "NXT-G",
            "Q",
            "PostScript",
            "HTML",
            "CSS",
            "jQuery",
            "Bootstrap",
            "React",
            "AngularJS",
            "Vue.js",
            "Ember.js",
            "Backbone.js",
            "Handlebars",
            "Knockout.js",
            "Mustache",
            "Underscore.js",
            "Polymer",
            "Svelte",
            "Rivets.js",
            "Stapes.js",
            "CanJS",
            "D3.js",
            "Three.js",
            "Pixi.js",
            "Phaser",
            "Babylon.js",
            "PlayCanvas",
            "Cesium",
            "A-Frame",
            "Enzyme",
            "Jest",
            "Mocha",
            "Chai",
            "Sinon",
            "Jasmine",
            "QUnit",
            "Karma",
            "NUnit",
            "MSTest",
            "XUnit",
            "JUnit",
            "PHPUnit",
            "Cucumber",
            "Protractor",
            "Selenium",
            "WebDriverIO",
            "Appium",
            "Nightwatch.js",
            "TestCafe",
            "Cypress",
            "Puppeteer",
            "Playwright",
            "TestComplete",
            "Ranorex",
            "Applitools",
            "Ghost Inspector",
            "LambdaTest",
            "BrowserStack",
            "Sauce Labs",
            "CrossBrowserTesting",
            "Perfecto",
            "TestingBot",
            "Browserling",
            "Litmus",
            "Email On Acid",
            "Mailchimp",
            "Campaign Monitor",
            "Constant Contact",
            "Sendinblue",
            "MailerLite",
            "GetResponse",
            "AWeber",
            "ActiveCampaign",
            "Drip",
            "HubSpot",
            "Mailjet",
            "Spring",
            "Express",
            "Django",
            "Flask",
            "Rails",
            "Laravel",
            "CodeIgniter",
            "Yii",
            "CakePHP",
            "Zend Framework",
            "Slim",
            "Sinatra",
            "Tornado",
            "Pyramid",
            "Web2py",
            "Falcon",
            "Pylons",
            "Bottle",
            "CubicWeb",
            "TurboGears",
            "Morepath",
            "Hug",
            "Quart",
            "Sanic",
            "FastAPI",
            "Responder",
            "Starlette",
            "Bocadillo",
            "Masonite",
            "Trails",
            "Pyro",
            "Aiohttp",
            "Weppy",
            "CherryPy",
            "Beaker",
            "WebCore",
            "WebOb",
            "Paste",
            "WebTest",
            "Oracle",
            "SQL Server",
            "PostgreSQL",
            "MongoDB",
            "MariaDB",
            "SQLite",
            "Redis",
            "Elasticsearch",
            "Cassandra",
            "Neo4j",
            "HBase",
            "Couchbase",
            "Firebase",
            "DB2",
            "Sybase",
            "Teradata",
            "Informix",
            "Ingres",
            "Greenplum",
            "MySql",
        ];

        foreach ($techSkills as $techSkill) {
            TechSkill::insert([
                'name' => $techSkill,
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }
    }
}
